### PR TITLE
[WIP] Python3 compatibility

### PR DESCRIPTION
**Pull request by AdamIsrael**
Building off of the work of @dbarrosop, this pull request is focusing strictly on the changes required to introduce Python3 compatibility. In doing so, I've dropped some of the initial changes (such as the use of OrderedDicts to guarantee the order of dictionary results) that are better proposed in a separate pull request, if someone feels strongly about those changes.

Outstanding items to address:
- [ ] Fix test - serialise/ietf-json-deserialise
- [ ] Fix test - serialise/json-deserialise
- [ ] Fix test - serialise/openconfig-serialise (also broken in master)
- [x] Fix test - integration/openconfig-interfaces
- [ ] Confirm all tests pass with Python3

### CODE REVIEW

**Comment by dbarrosop** [comment]
> I've dropped some of the initial changes (such as the use of OrderedDicts to guarantee the order of dictionary results) that are better proposed in a separate pull request

Sounds good to me, will send a new PR with only that soon. Let me know if you removed something else as well, please.

**Comment by robshakir** [comment]
On the CLA, the other submitter is @dbarrosop - so we're all good on CLA coverage. Thanks to both of you.

**Comment by tarkatronic** [comment]
@AdamIsrael As I previously mentioned, I'd love to help out with this effort. For easy coordination of efforts, might I suggest the Network To Code Slack instance?

Also, @robshakir, I can't seem to find the CLA for this project. Any pointers there?

**Comment by robshakir** [comment]
@tarkatronic The CLA is the Google CLA that can be signed at https://cla.developers.google.com/clas

Just as background -- when I moved to Google, we wanted to make sure that the contributions to pyangbind were such that they would allow free use of the code under the Apache 2.0 license, with clarity around copyright and contributions. My initial post on the subject was [here](https://github.com/robshakir/pyangbind/issues/93). If there are any questions on this, please do let me know and I can either answer, or I can ask our OSS team here to help out.

I'm happy to discuss on the Network To Code Slack, do you want to create a channel there?

**Comment by tarkatronic** [comment]
@robshakir Great! I've created #pyangbind on Slack, and I'm working on getting added to GoDaddy's CCLA for Google.

**Comment by tarkatronic** [comment]
@AdamIsrael Thank you for the help in getting Python 3 compatibility! Closing this up now, as we've gotten the work completed in master now.

**Pull request closed without merging**
