### PR TITLE
IETF serialization option to add default values

### PR DESCRIPTION
**Pull request by asloboda-cisco**
I second the surprise with behaviour leaving out values that match default in ticket #120.  I made a change to IETF serialization that allows me to modify this behaviour to do what I expected.  I added "with_default" argument which you suggested.

Please take a look.

### CODE REVIEW

**Comment by robshakir** [comment]
Thanks for the contribution -- if you could sign the CLA referenced above, that'd be great such that the copyright and licensing for your contribution is clarified. This then looks pretty good to merge!

**Comment by asloboda-cisco** [comment]
I'll see what I can do about that CLA.  I'm fine with any license, I'm sure anyone who is a little bit familiar with the code can make the same change in about 5 minutes.

**Comment by asloboda-cisco** [comment]
I'll see what I can do about that CLA.  I'm fine with any license, I'm sure anyone familiar with the code can make the same option in about 5 minutes.

**Comment by asloboda-cisco** [comment]
My employer says it was taken care of but I doubt googlebot will be happy with any of the e-mail addresses for this github account.  Let's see.

**Comment by asloboda-cisco** [comment]
Tried to reapply changes, let's see if this will appease googlebot.

**Comment by robshakir** [comment]
Hi @asloboda-cisco  -- this looks to be a duplicate, can we close it?

**Pull request closed without merging**
