### PR TITLE
Recursive addition of classes in building identities.

### PR DESCRIPTION
**Pull request by ashishk1994**
Fixes Bug: https://github.com/robshakir/pyangbind/issues/41

### CODE REVIEW

**Comment by robshakir** [comment]
Ashish,

Thanks for the work here -- I think this needs a little more examination. There are two problems that I think I can identity with the solution here:

1. The `for` loop that you've added appears to break the `while` loop that makes sure that we repeat the resolution process if the base does not exist.
2. I don't think that you can be sure that all the values have been added to the identity at the time that you do the inheritance. It seems like it needs to be done after all identities have been processed.

I'll take a look, as I do think #41 is an issue.

Cheers,
r.

**Comment by robshakir** [comment]
Hi Ashish,

I just resolved this and merged the fix, thanks for the pull-req. The recursive code I wrote resolves the two issues above.

Cheers,
r.

**Comment by ashishk1994** [comment]
@robshakir  Thanks a lot for adding my example :)

**Comment by robshakir** [comment]
No problem - I just cut v0.3.2, so this includes this fix.

**Pull request closed without merging**
