### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by eqvinox**
- ignore RestrictedPrecisionDecimal
- raise more specific "not found" in xpathhelper
- set zip_safe=False (plugin won't be found by pyang otherwise)

### CODE REVIEW

**Comment by robshakir** [comment]
Thanks!

Looks good -- one question, was there a specific error case in deserialisation that ignoring `RestrictedPrecisionDecimal` was? I'd like to add it to the unit tests.

Thanks for the contribution - will merge once we have the above unit test added :-)

r.

**Comment by eqvinox** [comment]
I don't know what exactly is causing the problem... I'm trying to load this json file (with `load()`):
```
{
    "neighbors": {
        "neighbor": {
            "192.168.1.100": {
                "neighbor-address": "192.168.1.100", 
                "config": {
                    "neighbor-address": "192.168.1.100", 
                    "peer-as": 64603
                },
		"timers": {
			"config": {
				"hold-time": 1900
			}
		}
            }, 
            "192.168.1.101": {
                "neighbor-address": "192.168.1.101", 
                "config": {
                    "neighbor-address": "192.168.1.101", 
                    "peer-as": 64603,
		    "description": "blazargh"
                }
            }, 
            "192.168.123.45": {
                "neighbor-address": "192.168.123.45", 
                "config": {
                    "neighbor-address": "192.168.123.45", 
                    "peer-as": 1234
                }
            }
        }
    }, 
    "global": {
        "config": {
            "as": 64603
        }, 
        "graceful-restart": {
            "config": {
                "stale-routes-time": 720.0, 
                "restart-time": 135
            }
        }
    }
}
```

and I get this exception:
```
Traceback (most recent call last):
  File "ocbgp.py", line 300, in <module>
    inp = pbj.load(args.load, bind.bgp, 'bgp', path_helper = ph)
  File "/home/equinox/.local/lib64/python2.7/site-packages/pyangbind-0.5.0-py2.7.egg/pyangbind/lib/pybindJSON.py", line 72, in load
    extmethods=extmethods, overwrite=overwrite)
  File "/home/equinox/.local/lib64/python2.7/site-packages/pyangbind-0.5.0-py2.7.egg/pyangbind/lib/pybindJSON.py", line 53, in loads
    path_helper=path_helper, extmethods=extmethods, overwrite=overwrite)
  File "/home/equinox/.local/lib64/python2.7/site-packages/pyangbind-0.5.0-py2.7.egg/pyangbind/lib/serialise.py", line 234, in load_json
    path_helper=path_helper)
  File "/home/equinox/.local/lib64/python2.7/site-packages/pyangbind-0.5.0-py2.7.egg/pyangbind/lib/serialise.py", line 269, in load_json
    obj=parent, path_helper=path_helper)
  File "/home/equinox/.local/lib64/python2.7/site-packages/pyangbind-0.5.0-py2.7.egg/pyangbind/lib/serialise.py", line 234, in load_json
    path_helper=path_helper)
  File "/home/equinox/.local/lib64/python2.7/site-packages/pyangbind-0.5.0-py2.7.egg/pyangbind/lib/serialise.py", line 234, in load_json
    path_helper=path_helper)
  File "/home/equinox/.local/lib64/python2.7/site-packages/pyangbind-0.5.0-py2.7.egg/pyangbind/lib/serialise.py", line 299, in load_json
    % pybind_attr)
pyangbind.lib.serialise.pybindJSONUpdateError: unknown pybind type when loading JSON: RestrictedPrecisionDecimal
```

Versions of models + pyang:
- https://github.com/YangModels/yang.git @ 300b617215e92232280812c77328ff1902692cea
- https://github.com/openconfig/public.git @ 06946f50a5b337f102fd77bcaced61c03cc1ba07
- https://github.com/mbj4668/pyang.git @ 6b56f6a743a247c3eaac5ef33201e29fb858ea3b (newer versions did not work because of an OpenConfig model problem)

**Comment by eqvinox** [comment]
Well, the existing "decimal" test already covers it, but unfortunately the test doesn't try deserializing from JSON, so it doesn't hit the failure... testcase extended now.

**Comment by robshakir** [comment]
@eqvinox Thanks for this -- all looks good. I merged the pull-request. Thanks again for the code :-)

Post merge, I moved the tests for decimal into the specific serialisation tests (under `tests/serialise`) and added them for serialisation + the IETF deserialisation.

Cheers,
r.

**Comment by eqvinox** [comment]
Eh, I managed to completely miss the "serialise" subdir... must be tomatoes on my eyes or something :D

**Comment by robshakir** [comment]
No problems! Even if you'd found it, it didn't have a test for this in it :-1:

**Pull request merged**
