### PR TITLE
Update yangtypes.py for all upper case bool

### PR DESCRIPTION
**Pull request by tejaskumark**
Sometime user input could be all upper case bool value.

### CODE REVIEW

**Comment by tejaskumark** [comment]
Can someone help me understand why my merge is failing because of environement variable issue?

**Comment by tejaskumark** [comment]
@robshakir Can you please help me to get this issue past?

**Comment by tejaskumark** [comment]
@googlebot I signed it!

**Comment by tarkatronic** [comment]
@tejaskumark The test failures are likely the ones which I encountered (and fixed) in #233. So once @robshakir gets that merged in, as long as you pull in the latest master branch, this should then pass.

**Comment by tejaskumark** [comment]
@robshakir Can you please help here with review for merge?

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please rebase to a recent versions of pyangbind ?

Thanks.

**Comment by JoseIgnacioTamayo** [comment]
Closing old PullRequest

**Pull request closed without merging**
