### PR TITLE
Support identities with multiple bases

### PR DESCRIPTION
**Pull request by dimbleby**
(This is allowed as at RFC7950).

### CODE REVIEW

**Comment by dimbleby** [comment]
I'm not sure how 'alive' this project is - it seems to have been a while since there was any activity.

But if there's any chance of a fresh release including this fix (#209 is also relevant)... that would be much appreciated - thanks!

**Comment by dimbleby** [comment]
Travis failures appear to be unrelated to this fix, please let me know if I'm wrong.

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please rebase to a recent versions of pyangbind ?

Thanks.

**Comment by dimbleby** [comment]
I have long since lost interest in pyangbind, sorry.

As far as I remember this fix was good when I made it and you are welcome to it if you want it: or just throw it away.

**Comment by JoseIgnacioTamayo** [comment]
Forked in https://github.com/robshakir/pyangbind/pull/331

**Comment by JoseIgnacioTamayo** [comment]
Discarding old PullRequest

**Pull request closed without merging**
