### PR TITLE
pep8 clean up

### PR DESCRIPTION
**Pull request by vnitinv**
My first pull request to pyangbind with [pep8](https://www.python.org/dev/peps/pep-0008/) cleanup using tool [autopep8](https://github.com/hhatto/autopep8)

### CODE REVIEW

**Comment by robshakir** [comment]
Hi,

It's pretty difficult to tell what this pull request actually does, other than changing the indentation style from two spaces to four. Can you give me some view on the motivation for this change, and a bit of a run through of what the other changes that the tool made are?

Cheers,
r.

**Comment by vnitinv** [comment]
If we run "pep8 ." under folder pyangbind, we can notice many type of pep8 violation 

for ex:
```
./tests/xpath/01-list_leaflist/run.py:72:21: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./tests/xpath/01-list_leaflist/run.py:72:80: E501 line too long (84 > 79 characters)
./tests/xpath/01-list_leaflist/run.py:73:7: E127 continuation line over-indented for visual indent
./tests/xpath/01-list_leaflist/run.py:75:3: E111 indentation is not a multiple of four
./tests/xpath/01-list_leaflist/run.py:78:1: E302 expected 2 blank lines, found 1
./tests/xpath/01-list_leaflist/run.py:78:17: E231 missing whitespace after ','
```
I do understand 90% of changes relate to space (2 to 4). I thought to clean it up as python developer uses IDE like PyCharm, IDLE etc which follows pep8 rule of 4 space. So in future once we have many contributor toward pyangbind there wont be mix of 2 & 4 spaces.

We can ignore this pull request as of now.

**Comment by vnitinv** [comment]
Rob, I am closing this pull request inline with #22 but I still go by my point "python developer uses IDE like PyCharm, IDLE etc which follows pep8 rule of 4 space. So in future once we have many contributor toward pyangbind there wont be mix of 2 & 4 spaces."

**Comment by robshakir** [comment]
@vnitinv 

I agree that this is not-PEP8 complaint, and there are people that might use IDEs/development environments where indentation style cannot be set. I'd expect users of pyangbind not to edit the generated code manually - so I'm not clear that a *user* would care. If there are others that want to contribute to pyangbind that find this a problem, then we can reconsider.

**Pull request closed without merging**
