### PR TITLE
Potential bugfix for #232

### PR DESCRIPTION
**Pull request by tarkatronic**
This is the proposed fix for #232 although I am still rather concerned that we don't have any tests which expose this reported issue.

I also had to do some small updates for the latest openconfig model changes.

And I included a minor version bump because, with this release, the xml serialization will be released as well!

### CODE REVIEW

**Comment by kqchen34** [comment]
I tested using the branch tarkatronic:issue-232, it does fix the issue mentioned in issue-232. Thanks!

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please rebase to a recent versions of pyangbind ?

Thanks.

**Comment by tarkatronic** [comment]
> Hi,
> 
> Could you please rebase to a recent versions of pyangbind ?
> 
> Thanks.

Hi @JoseIgnacioTamayo, I have not used pyangbind in many years now, and am therefore no longer involved in the development. If this is still found to be a useful bugfix, I would encourage you to take over this change. Thank you!

**Comment by JoseIgnacioTamayo** [comment]
https://github.com/robshakir/pyangbind/issues/232 was closed.

**Pull request closed without merging**
